#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch Leveque.foam
wmake libso generateU

runApplication blockMesh
restore0Dir

runApplication setAlphaField
runApplication generateU

if [ "$1" = "-test" ]
then
    runApplication $(getApplication)
else
    runApplication decomposePar
    runParallel $(getApplication)
fi

