#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch sinWave.foam

restore0Dir
runApplication blockMesh

runApplication setAlphaField
runApplication $(getApplication)

#------------------------------------------------------------------------------
