#!/bin/bash

wmake libso src/stencil
wmake libso src/interfaceCapturing
wmake libso src/surfaceForces

wmake libso src/postProcessing

wmake applications/benchmark/interfaceAdvector
wmake applications/benchmark/reconstructInterface

wmake applications/solver/interCapturingFoam

