#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch sinWaveTet.foam

restore0Dir
runApplication gmshv493 -3 triSquare.geo
runApplication gmshToFoam triSquare.msh
runApplication changeDictionary 
runApplication transformPoints -rollPitchYaw '(90.0 0 0)'

runApplication setAlphaField
#runApplication decomposePar
runApplication $(getApplication)
#sbatch Allrun_Slurm

#------------------------------------------------------------------------------
