#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
restore0Dir
touch advectCircle.foam
runApplication gmshv493 -3 triSquare.geo
runApplication gmshToFoam triSquare.msh
runApplication changeDictionary 


runApplication setAlphaField

if [ "$1" = "-test" ]
then
    runApplication $(getApplication)
else
    runApplication decomposePar
    runParallel $(getApplication)
fi

#------------------------------------------------------------------------------
