#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
restore0Dir
touch advectCircle.foam
runApplication blockMesh

runApplication setAlphaField
runApplication decomposePar
runParallel $(getApplication)
#sbatch Allrun_Slurm

#------------------------------------------------------------------------------
