#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions
application=$(sed -ne "s/^application\s*\(.*\);/\1/p" system/controlDict)
touch circle.foam

runApplication gmshv493 -3 triBlock.geo
runApplication gmshToFoam triBlock.msh
# runApplication changeDictionary
restore0Dir

runApplication $(getApplication)
cp postProcessing/reconstructionError/0/error.dat error.dat

